# Use an official Node.js runtime as the base image
FROM node:20.18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 8080
EXPOSE 3000

# Specify the user to run the container as
USER node

# Define the command to run the application
CMD ["npm", "run" , "dev"]