# Use an official Node.js runtime as the base image
FROM node:20.18

# Set the working directory in the container
WORKDIR /app

# Copy and install dependencies as root
COPY package*.json ./

RUN npm install && npm install -g ts-node
# Copy the rest of the application code
COPY . .

# Change ownership and switch to the 'node' user
RUN chown -R node:node /app
USER node

# Expose port 5000
EXPOSE 5000

# Define the command to run the application
CMD ["npm", "start"]
